2022-03-11 04:59:33,784 INFO    Thread-7  :46628 [wandb_setup.py:_flush():69] setting env: {'project': 'L-tune', 'entity': 'wtmlon', 'root_dir': '/lt/DART', 'run_id': 'bux9vq0e', 'sweep_param_path': '/lt/DART/wandb/sweep-fm5wnjye/config-bux9vq0e.yaml', 'sweep_id': 'fm5wnjye'}
2022-03-11 04:59:33,784 INFO    Thread-7  :46628 [wandb_init.py:_log_setup():336] Logging user logs to /lt/DART/wandb/run-20220311_045933-bux9vq0e/logs/debug.log
2022-03-11 04:59:33,785 INFO    Thread-7  :46628 [wandb_init.py:_log_setup():337] Logging internal logs to /lt/DART/wandb/run-20220311_045933-bux9vq0e/logs/debug-internal.log
2022-03-11 04:59:33,785 INFO    Thread-7  :46628 [wandb_init.py:init():369] calling init triggers
2022-03-11 04:59:33,785 INFO    Thread-7  :46628 [wandb_init.py:init():374] wandb.init called with sweep_config: {'batch_size': 4, 'encoder_type': 'mlp', 'learning_rate': 1e-06, 'seed_split': 13, 'task': 'SST-2', 'weight_decay': 0.01, 'x_input': 'mix'}
config: {}
2022-03-11 04:59:33,785 INFO    Thread-7  :46628 [wandb_init.py:init():418] starting backend
2022-03-11 04:59:33,785 INFO    Thread-7  :46628 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-11 04:59:33,791 INFO    Thread-7  :46628 [backend.py:ensure_launched():132] starting backend process...
2022-03-11 04:59:33,806 INFO    Thread-7  :46628 [backend.py:ensure_launched():136] started backend process with pid: 46854
2022-03-11 04:59:33,808 INFO    Thread-7  :46628 [wandb_init.py:init():423] backend started and connected
2022-03-11 04:59:33,809 INFO    Thread-7  :46628 [wandb_run.py:_config_callback():787] config_cb None None {'batch_size': 4, 'encoder_type': 'mlp', 'learning_rate': 1e-06, 'seed_split': 13, 'task': 'SST-2', 'weight_decay': 0.01, 'x_input': 'mix'}
2022-03-11 04:59:33,810 INFO    Thread-7  :46628 [wandb_init.py:init():465] updated telemetry
2022-03-11 04:59:33,810 INFO    Thread-7  :46628 [wandb_init.py:init():484] communicating current version
2022-03-11 04:59:38,811 INFO    Thread-7  :46628 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2022-03-11 05:00:03,668 INFO    Thread-7  :46628 [wandb_init.py:init():522] starting run threads in backend
2022-03-11 05:00:08,678 INFO    Thread-7  :46628 [wandb_run.py:_console_start():1565] atexit reg
2022-03-11 05:00:08,679 INFO    Thread-7  :46628 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2022-03-11 05:00:08,680 INFO    Thread-7  :46628 [wandb_run.py:_redirect():1417] Redirecting console.
2022-03-11 05:00:08,681 ERROR   Thread-7  :46628 [wandb_run.py:_redirect():1482] Failed to redirect.
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1475, in _redirect
    out_redir.install()
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 605, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 555, in add_fd
    self._register()
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 540, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/root/anaconda3/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2022-03-11 05:00:08,683 INFO    Thread-7  :46628 [wandb_init.py:init():546] run started, returning control to user process
2022-03-11 05:00:09,631 INFO    Thread-12 :46628 [wandb_setup.py:_flush():69] setting env: {'project': 'L-tune', 'entity': 'wtmlon', 'root_dir': '/lt/DART', 'run_id': 'maax43on', 'sweep_param_path': '/lt/DART/wandb/sweep-fm5wnjye/config-maax43on.yaml', 'sweep_id': 'fm5wnjye'}
2022-03-11 05:00:09,632 INFO    Thread-12 :46628 [wandb_init.py:_log_setup():336] Logging user logs to /lt/DART/wandb/run-20220311_050009-maax43on/logs/debug.log
2022-03-11 05:00:09,632 INFO    Thread-12 :46628 [wandb_init.py:_log_setup():337] Logging internal logs to /lt/DART/wandb/run-20220311_050009-maax43on/logs/debug-internal.log
2022-03-11 05:00:09,632 INFO    Thread-12 :46628 [wandb_init.py:init():369] calling init triggers
2022-03-11 05:00:09,633 INFO    Thread-12 :46628 [wandb_init.py:init():374] wandb.init called with sweep_config: {'batch_size': 4, 'encoder_type': 'mlp', 'learning_rate': 1e-06, 'seed_split': 13, 'task': 'SST-2', 'weight_decay': 0.05, 'x_input': 'mix'}
config: {}
2022-03-11 05:00:09,633 INFO    Thread-12 :46628 [wandb_init.py:init():418] starting backend
2022-03-11 05:00:09,633 INFO    Thread-12 :46628 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-11 05:00:09,639 INFO    Thread-12 :46628 [backend.py:ensure_launched():132] starting backend process...
2022-03-11 05:00:09,650 INFO    Thread-12 :46628 [backend.py:ensure_launched():136] started backend process with pid: 46943
2022-03-11 05:00:09,651 INFO    Thread-12 :46628 [wandb_init.py:init():423] backend started and connected
2022-03-11 05:00:09,652 INFO    Thread-12 :46628 [wandb_run.py:_config_callback():787] config_cb None None {'batch_size': 4, 'encoder_type': 'mlp', 'learning_rate': 1e-06, 'seed_split': 13, 'task': 'SST-2', 'weight_decay': 0.05, 'x_input': 'mix'}
2022-03-11 05:00:09,653 INFO    Thread-12 :46628 [wandb_init.py:init():465] updated telemetry
2022-03-11 05:00:09,653 INFO    Thread-12 :46628 [wandb_init.py:init():484] communicating current version
2022-03-11 05:00:14,654 INFO    Thread-12 :46628 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2022-03-11 05:00:39,428 INFO    Thread-12 :46628 [wandb_init.py:init():522] starting run threads in backend
2022-03-11 05:00:44,438 INFO    Thread-12 :46628 [wandb_run.py:_console_start():1565] atexit reg
2022-03-11 05:00:44,439 INFO    Thread-12 :46628 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2022-03-11 05:00:44,440 INFO    Thread-12 :46628 [wandb_run.py:_redirect():1417] Redirecting console.
2022-03-11 05:00:44,442 ERROR   Thread-12 :46628 [wandb_run.py:_redirect():1482] Failed to redirect.
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1475, in _redirect
    out_redir.install()
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 605, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 555, in add_fd
    self._register()
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 540, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/root/anaconda3/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2022-03-11 05:00:44,443 INFO    Thread-12 :46628 [wandb_init.py:init():546] run started, returning control to user process
2022-03-11 05:00:45,457 INFO    Thread-17 :46628 [wandb_setup.py:_flush():69] setting env: {'project': 'L-tune', 'entity': 'wtmlon', 'root_dir': '/lt/DART', 'run_id': 'dn2m009l', 'sweep_param_path': '/lt/DART/wandb/sweep-fm5wnjye/config-dn2m009l.yaml', 'sweep_id': 'fm5wnjye'}
2022-03-11 05:00:45,458 INFO    Thread-17 :46628 [wandb_init.py:_log_setup():336] Logging user logs to /lt/DART/wandb/run-20220311_050045-dn2m009l/logs/debug.log
2022-03-11 05:00:45,458 INFO    Thread-17 :46628 [wandb_init.py:_log_setup():337] Logging internal logs to /lt/DART/wandb/run-20220311_050045-dn2m009l/logs/debug-internal.log
2022-03-11 05:00:45,458 INFO    Thread-17 :46628 [wandb_init.py:init():369] calling init triggers
2022-03-11 05:00:45,458 INFO    Thread-17 :46628 [wandb_init.py:init():374] wandb.init called with sweep_config: {'batch_size': 4, 'encoder_type': 'mlp', 'learning_rate': 1e-06, 'seed_split': 13, 'task': 'SST-2', 'weight_decay': 0.1, 'x_input': 'mix'}
config: {}
2022-03-11 05:00:45,459 INFO    Thread-17 :46628 [wandb_init.py:init():418] starting backend
2022-03-11 05:00:45,459 INFO    Thread-17 :46628 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-11 05:00:45,465 INFO    Thread-17 :46628 [backend.py:ensure_launched():132] starting backend process...
2022-03-11 05:00:45,477 INFO    Thread-17 :46628 [backend.py:ensure_launched():136] started backend process with pid: 47040
2022-03-11 05:00:45,478 INFO    Thread-17 :46628 [wandb_init.py:init():423] backend started and connected
2022-03-11 05:00:45,480 INFO    Thread-17 :46628 [wandb_run.py:_config_callback():787] config_cb None None {'batch_size': 4, 'encoder_type': 'mlp', 'learning_rate': 1e-06, 'seed_split': 13, 'task': 'SST-2', 'weight_decay': 0.1, 'x_input': 'mix'}
2022-03-11 05:00:45,480 INFO    Thread-17 :46628 [wandb_init.py:init():465] updated telemetry
2022-03-11 05:00:45,481 INFO    Thread-17 :46628 [wandb_init.py:init():484] communicating current version
2022-03-11 05:00:50,482 INFO    Thread-17 :46628 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2022-03-11 05:00:51,685 INFO    Thread-17 :46628 [wandb_init.py:init():522] starting run threads in backend
2022-03-11 05:00:56,693 INFO    Thread-17 :46628 [wandb_run.py:_console_start():1565] atexit reg
2022-03-11 05:00:56,695 INFO    Thread-17 :46628 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2022-03-11 05:00:56,696 INFO    Thread-17 :46628 [wandb_run.py:_redirect():1417] Redirecting console.
2022-03-11 05:00:56,697 ERROR   Thread-17 :46628 [wandb_run.py:_redirect():1482] Failed to redirect.
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1475, in _redirect
    out_redir.install()
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 605, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 555, in add_fd
    self._register()
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 540, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/root/anaconda3/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2022-03-11 05:00:56,698 INFO    Thread-17 :46628 [wandb_init.py:init():546] run started, returning control to user process
2022-03-11 05:00:57,801 INFO    Thread-22 :46628 [wandb_setup.py:_flush():69] setting env: {'project': 'L-tune', 'entity': 'wtmlon', 'root_dir': '/lt/DART', 'run_id': 'ppqic7n2', 'sweep_param_path': '/lt/DART/wandb/sweep-fm5wnjye/config-ppqic7n2.yaml', 'sweep_id': 'fm5wnjye'}
2022-03-11 05:00:57,802 INFO    Thread-22 :46628 [wandb_init.py:_log_setup():336] Logging user logs to /lt/DART/wandb/run-20220311_050057-ppqic7n2/logs/debug.log
2022-03-11 05:00:57,802 INFO    Thread-22 :46628 [wandb_init.py:_log_setup():337] Logging internal logs to /lt/DART/wandb/run-20220311_050057-ppqic7n2/logs/debug-internal.log
2022-03-11 05:00:57,802 INFO    Thread-22 :46628 [wandb_init.py:init():369] calling init triggers
2022-03-11 05:00:57,803 INFO    Thread-22 :46628 [wandb_init.py:init():374] wandb.init called with sweep_config: {'batch_size': 4, 'encoder_type': 'mlp', 'learning_rate': 1e-06, 'seed_split': 21, 'task': 'SST-2', 'weight_decay': 0, 'x_input': 'mix'}
config: {}
2022-03-11 05:00:57,803 INFO    Thread-22 :46628 [wandb_init.py:init():418] starting backend
2022-03-11 05:00:57,803 INFO    Thread-22 :46628 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-11 05:00:57,809 INFO    Thread-22 :46628 [backend.py:ensure_launched():132] starting backend process...
2022-03-11 05:00:57,819 INFO    Thread-22 :46628 [backend.py:ensure_launched():136] started backend process with pid: 47129
2022-03-11 05:00:57,821 INFO    Thread-22 :46628 [wandb_init.py:init():423] backend started and connected
2022-03-11 05:00:57,822 INFO    Thread-22 :46628 [wandb_run.py:_config_callback():787] config_cb None None {'batch_size': 4, 'encoder_type': 'mlp', 'learning_rate': 1e-06, 'seed_split': 21, 'task': 'SST-2', 'weight_decay': 0, 'x_input': 'mix'}
2022-03-11 05:00:57,823 INFO    Thread-22 :46628 [wandb_init.py:init():465] updated telemetry
2022-03-11 05:00:57,824 INFO    Thread-22 :46628 [wandb_init.py:init():484] communicating current version
2022-03-11 05:01:02,825 INFO    Thread-22 :46628 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2022-03-11 05:01:04,040 INFO    Thread-22 :46628 [wandb_init.py:init():522] starting run threads in backend
2022-03-11 05:01:09,050 INFO    Thread-22 :46628 [wandb_run.py:_console_start():1565] atexit reg
2022-03-11 05:01:09,052 INFO    Thread-22 :46628 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2022-03-11 05:01:09,053 INFO    Thread-22 :46628 [wandb_run.py:_redirect():1417] Redirecting console.
2022-03-11 05:01:09,054 ERROR   Thread-22 :46628 [wandb_run.py:_redirect():1482] Failed to redirect.
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1475, in _redirect
    out_redir.install()
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 605, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 555, in add_fd
    self._register()
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 540, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/root/anaconda3/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2022-03-11 05:01:09,056 INFO    Thread-22 :46628 [wandb_init.py:init():546] run started, returning control to user process
2022-03-11 05:01:10,076 INFO    Thread-27 :46628 [wandb_setup.py:_flush():69] setting env: {'project': 'L-tune', 'entity': 'wtmlon', 'root_dir': '/lt/DART', 'run_id': 'gsbl7qzu', 'sweep_param_path': '/lt/DART/wandb/sweep-fm5wnjye/config-gsbl7qzu.yaml', 'sweep_id': 'fm5wnjye'}
2022-03-11 05:01:10,077 INFO    Thread-27 :46628 [wandb_init.py:_log_setup():336] Logging user logs to /lt/DART/wandb/run-20220311_050110-gsbl7qzu/logs/debug.log
2022-03-11 05:01:10,077 INFO    Thread-27 :46628 [wandb_init.py:_log_setup():337] Logging internal logs to /lt/DART/wandb/run-20220311_050110-gsbl7qzu/logs/debug-internal.log
2022-03-11 05:01:10,077 INFO    Thread-27 :46628 [wandb_init.py:init():369] calling init triggers
2022-03-11 05:01:10,078 INFO    Thread-27 :46628 [wandb_init.py:init():374] wandb.init called with sweep_config: {'batch_size': 4, 'encoder_type': 'mlp', 'learning_rate': 1e-06, 'seed_split': 21, 'task': 'SST-2', 'weight_decay': 0.01, 'x_input': 'mix'}
config: {}
2022-03-11 05:01:10,078 INFO    Thread-27 :46628 [wandb_init.py:init():418] starting backend
2022-03-11 05:01:10,078 INFO    Thread-27 :46628 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-11 05:01:10,084 INFO    Thread-27 :46628 [backend.py:ensure_launched():132] starting backend process...
2022-03-11 05:01:10,105 INFO    Thread-27 :46628 [backend.py:ensure_launched():136] started backend process with pid: 47226
2022-03-11 05:01:10,107 INFO    Thread-27 :46628 [wandb_init.py:init():423] backend started and connected
2022-03-11 05:01:10,109 INFO    Thread-27 :46628 [wandb_run.py:_config_callback():787] config_cb None None {'batch_size': 4, 'encoder_type': 'mlp', 'learning_rate': 1e-06, 'seed_split': 21, 'task': 'SST-2', 'weight_decay': 0.01, 'x_input': 'mix'}
2022-03-11 05:01:10,110 INFO    Thread-27 :46628 [wandb_init.py:init():465] updated telemetry
2022-03-11 05:01:10,111 INFO    Thread-27 :46628 [wandb_init.py:init():484] communicating current version
2022-03-11 05:01:15,112 INFO    Thread-27 :46628 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2022-03-11 05:01:16,306 INFO    Thread-27 :46628 [wandb_init.py:init():522] starting run threads in backend
2022-03-11 05:01:21,315 INFO    Thread-27 :46628 [wandb_run.py:_console_start():1565] atexit reg
2022-03-11 05:01:21,316 INFO    Thread-27 :46628 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2022-03-11 05:01:21,317 INFO    Thread-27 :46628 [wandb_run.py:_redirect():1417] Redirecting console.
2022-03-11 05:01:21,318 ERROR   Thread-27 :46628 [wandb_run.py:_redirect():1482] Failed to redirect.
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1475, in _redirect
    out_redir.install()
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 605, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 555, in add_fd
    self._register()
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 540, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/root/anaconda3/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2022-03-11 05:01:21,319 INFO    Thread-27 :46628 [wandb_init.py:init():546] run started, returning control to user process
2022-03-11 05:01:22,702 INFO    Thread-32 :46628 [wandb_setup.py:_flush():69] setting env: {'project': 'L-tune', 'entity': 'wtmlon', 'root_dir': '/lt/DART', 'run_id': 'n5pxqen5', 'sweep_param_path': '/lt/DART/wandb/sweep-fm5wnjye/config-n5pxqen5.yaml', 'sweep_id': 'fm5wnjye'}
2022-03-11 05:01:22,703 INFO    Thread-32 :46628 [wandb_init.py:_log_setup():336] Logging user logs to /lt/DART/wandb/run-20220311_050122-n5pxqen5/logs/debug.log
2022-03-11 05:01:22,703 INFO    Thread-32 :46628 [wandb_init.py:_log_setup():337] Logging internal logs to /lt/DART/wandb/run-20220311_050122-n5pxqen5/logs/debug-internal.log
2022-03-11 05:01:22,704 INFO    Thread-32 :46628 [wandb_init.py:init():369] calling init triggers
2022-03-11 05:01:22,704 INFO    Thread-32 :46628 [wandb_init.py:init():374] wandb.init called with sweep_config: {'batch_size': 4, 'encoder_type': 'mlp', 'learning_rate': 1e-06, 'seed_split': 21, 'task': 'SST-2', 'weight_decay': 0.05, 'x_input': 'mix'}
config: {}
2022-03-11 05:01:22,704 INFO    Thread-32 :46628 [wandb_init.py:init():418] starting backend
2022-03-11 05:01:22,704 INFO    Thread-32 :46628 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-11 05:01:22,710 INFO    Thread-32 :46628 [backend.py:ensure_launched():132] starting backend process...
2022-03-11 05:01:22,722 INFO    Thread-32 :46628 [backend.py:ensure_launched():136] started backend process with pid: 47315
2022-03-11 05:01:22,724 INFO    Thread-32 :46628 [wandb_init.py:init():423] backend started and connected
2022-03-11 05:01:22,725 INFO    Thread-32 :46628 [wandb_run.py:_config_callback():787] config_cb None None {'batch_size': 4, 'encoder_type': 'mlp', 'learning_rate': 1e-06, 'seed_split': 21, 'task': 'SST-2', 'weight_decay': 0.05, 'x_input': 'mix'}
2022-03-11 05:01:22,726 INFO    Thread-32 :46628 [wandb_init.py:init():465] updated telemetry
2022-03-11 05:01:22,727 INFO    Thread-32 :46628 [wandb_init.py:init():484] communicating current version
2022-03-11 05:01:27,728 INFO    Thread-32 :46628 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2022-03-11 05:01:28,899 INFO    Thread-32 :46628 [wandb_init.py:init():522] starting run threads in backend
2022-03-11 05:01:33,908 INFO    Thread-32 :46628 [wandb_run.py:_console_start():1565] atexit reg
2022-03-11 05:01:33,910 INFO    Thread-32 :46628 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2022-03-11 05:01:33,910 INFO    Thread-32 :46628 [wandb_run.py:_redirect():1417] Redirecting console.
2022-03-11 05:01:33,912 ERROR   Thread-32 :46628 [wandb_run.py:_redirect():1482] Failed to redirect.
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1475, in _redirect
    out_redir.install()
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 605, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 555, in add_fd
    self._register()
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 540, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/root/anaconda3/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2022-03-11 05:01:33,913 INFO    Thread-32 :46628 [wandb_init.py:init():546] run started, returning control to user process
2022-03-11 05:01:53,214 INFO    Thread-37 :46628 [wandb_setup.py:_flush():69] setting env: {'project': 'L-tune', 'entity': 'wtmlon', 'root_dir': '/lt/DART', 'run_id': 'wa7hp057', 'sweep_param_path': '/lt/DART/wandb/sweep-fm5wnjye/config-wa7hp057.yaml', 'sweep_id': 'fm5wnjye'}
2022-03-11 05:01:53,215 INFO    Thread-37 :46628 [wandb_init.py:_log_setup():336] Logging user logs to /lt/DART/wandb/run-20220311_050153-wa7hp057/logs/debug.log
2022-03-11 05:01:53,216 INFO    Thread-37 :46628 [wandb_init.py:_log_setup():337] Logging internal logs to /lt/DART/wandb/run-20220311_050153-wa7hp057/logs/debug-internal.log
2022-03-11 05:01:53,216 INFO    Thread-37 :46628 [wandb_init.py:init():369] calling init triggers
2022-03-11 05:01:53,216 INFO    Thread-37 :46628 [wandb_init.py:init():374] wandb.init called with sweep_config: {'batch_size': 4, 'encoder_type': 'mlp', 'learning_rate': 1e-06, 'seed_split': 21, 'task': 'SST-2', 'weight_decay': 0.1, 'x_input': 'mix'}
config: {}
2022-03-11 05:01:53,217 INFO    Thread-37 :46628 [wandb_init.py:init():418] starting backend
2022-03-11 05:01:53,217 INFO    Thread-37 :46628 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-11 05:01:53,223 INFO    Thread-37 :46628 [backend.py:ensure_launched():132] starting backend process...
2022-03-11 05:01:53,235 INFO    Thread-37 :46628 [backend.py:ensure_launched():136] started backend process with pid: 47404
2022-03-11 05:01:53,237 INFO    Thread-37 :46628 [wandb_init.py:init():423] backend started and connected
2022-03-11 05:01:53,238 INFO    Thread-37 :46628 [wandb_run.py:_config_callback():787] config_cb None None {'batch_size': 4, 'encoder_type': 'mlp', 'learning_rate': 1e-06, 'seed_split': 21, 'task': 'SST-2', 'weight_decay': 0.1, 'x_input': 'mix'}
2022-03-11 05:01:53,239 INFO    Thread-37 :46628 [wandb_init.py:init():465] updated telemetry
2022-03-11 05:01:53,240 INFO    Thread-37 :46628 [wandb_init.py:init():484] communicating current version
2022-03-11 05:01:58,241 INFO    Thread-37 :46628 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2022-03-11 05:01:59,459 INFO    Thread-37 :46628 [wandb_init.py:init():522] starting run threads in backend
2022-03-11 05:02:04,477 ERROR   Thread-37 :46628 [wandb_init.py:init():770] error
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 744, in init
    run = wi.init()
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 525, in init
    _ = backend.interface.communicate_run_start(run_obj)
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 799, in communicate_run_start
    result = self._communicate(rec)
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 537, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 82, in get
    is_set = self._object_ready.wait(timeout)
  File "/root/anaconda3/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/root/anaconda3/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
Exception
2022-03-11 05:02:06,485 INFO    Thread-37 :46628 [wandb_run.py:finish():1208] finishing run wtmlon/L-tune/n5pxqen5
2022-03-11 05:02:06,486 INFO    Thread-37 :46628 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 1
2022-03-11 05:02:06,487 INFO    Thread-37 :46628 [wandb_run.py:_restore():1507] restore
2022-03-11 05:02:06,487 INFO    Thread-37 :46628 [wandb_run.py:_restore():1507] restore
2022-03-11 05:02:06,498 INFO    MainThread:46628 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 2
2022-03-11 05:02:06,498 INFO    MainThread:46628 [wandb_run.py:_restore():1507] restore
2022-03-11 05:02:06,499 INFO    MainThread:46628 [wandb_run.py:_restore():1507] restore
2022-03-11 05:02:06,504 INFO    MainThread:46628 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 2
2022-03-11 05:02:06,504 INFO    MainThread:46628 [wandb_run.py:_restore():1507] restore
2022-03-11 05:02:06,504 INFO    MainThread:46628 [wandb_run.py:_restore():1507] restore
2022-03-11 05:02:06,509 INFO    MainThread:46628 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 2
2022-03-11 05:02:06,509 INFO    MainThread:46628 [wandb_run.py:_restore():1507] restore
2022-03-11 05:02:06,510 INFO    MainThread:46628 [wandb_run.py:_restore():1507] restore
2022-03-11 05:02:06,514 INFO    MainThread:46628 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 2
2022-03-11 05:02:06,514 INFO    MainThread:46628 [wandb_run.py:_restore():1507] restore
2022-03-11 05:02:06,515 INFO    MainThread:46628 [wandb_run.py:_restore():1507] restore
2022-03-11 05:02:06,518 INFO    MainThread:46628 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 2
2022-03-11 05:02:06,518 INFO    MainThread:46628 [wandb_run.py:_restore():1507] restore
2022-03-11 05:02:06,518 INFO    MainThread:46628 [wandb_run.py:_restore():1507] restore
2022-03-11 05:02:06,521 INFO    MainThread:46628 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 2
2022-03-11 05:02:06,521 INFO    MainThread:46628 [wandb_run.py:_restore():1507] restore
2022-03-11 05:02:06,522 INFO    MainThread:46628 [wandb_run.py:_restore():1507] restore
