2022-03-11 05:06:10,919 INFO    Thread-2  :47816 [wandb_setup.py:_flush():69] setting env: {'project': 'L-tune', 'entity': 'wtmlon', 'root_dir': '/lt/DART', 'sweep_id': 'in2rb94g', 'run_id': 'korcoia0', 'sweep_param_path': '/lt/DART/wandb/sweep-in2rb94g/config-korcoia0.yaml'}
2022-03-11 05:06:10,919 INFO    Thread-2  :47816 [wandb_setup.py:_flush():69] setting login settings: {}
2022-03-11 05:06:10,920 INFO    Thread-2  :47816 [wandb_init.py:_log_setup():336] Logging user logs to /lt/DART/wandb/run-20220311_050610-korcoia0/logs/debug.log
2022-03-11 05:06:10,920 INFO    Thread-2  :47816 [wandb_init.py:_log_setup():337] Logging internal logs to /lt/DART/wandb/run-20220311_050610-korcoia0/logs/debug-internal.log
2022-03-11 05:06:10,920 INFO    Thread-2  :47816 [wandb_init.py:init():369] calling init triggers
2022-03-11 05:06:10,920 INFO    Thread-2  :47816 [wandb_init.py:init():374] wandb.init called with sweep_config: {'batch_size': 4, 'encoder_type': 'mlp', 'learning_rate': 1e-06, 'seed_split': 13, 'task': 'SST-2', 'weight_decay': 0, 'x_input': 'mix'}
config: {}
2022-03-11 05:06:10,920 INFO    Thread-2  :47816 [wandb_init.py:init():418] starting backend
2022-03-11 05:06:10,920 INFO    Thread-2  :47816 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-11 05:06:10,937 INFO    Thread-2  :47816 [backend.py:ensure_launched():132] starting backend process...
2022-03-11 05:06:10,952 INFO    Thread-2  :47816 [backend.py:ensure_launched():136] started backend process with pid: 47953
2022-03-11 05:06:10,953 INFO    Thread-2  :47816 [wandb_init.py:init():423] backend started and connected
2022-03-11 05:06:10,954 INFO    Thread-2  :47816 [wandb_run.py:_config_callback():787] config_cb None None {'batch_size': 4, 'encoder_type': 'mlp', 'learning_rate': 1e-06, 'seed_split': 13, 'task': 'SST-2', 'weight_decay': 0, 'x_input': 'mix'}
2022-03-11 05:06:10,955 INFO    Thread-2  :47816 [wandb_init.py:init():465] updated telemetry
2022-03-11 05:06:10,955 INFO    Thread-2  :47816 [wandb_init.py:init():484] communicating current version
2022-03-11 05:06:15,956 INFO    Thread-2  :47816 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2022-03-11 05:06:17,096 INFO    Thread-2  :47816 [wandb_init.py:init():522] starting run threads in backend
2022-03-11 05:06:22,104 INFO    Thread-2  :47816 [wandb_run.py:_console_start():1565] atexit reg
2022-03-11 05:06:22,106 INFO    Thread-2  :47816 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2022-03-11 05:06:22,106 INFO    Thread-2  :47816 [wandb_run.py:_redirect():1417] Redirecting console.
2022-03-11 05:06:22,109 ERROR   Thread-2  :47816 [wandb_run.py:_redirect():1482] Failed to redirect.
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1475, in _redirect
    out_redir.install()
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 605, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 555, in add_fd
    self._register()
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 540, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/root/anaconda3/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2022-03-11 05:06:22,111 INFO    Thread-2  :47816 [wandb_init.py:init():546] run started, returning control to user process
2022-03-11 05:06:23,433 INFO    Thread-7  :47816 [wandb_setup.py:_flush():69] setting env: {'project': 'L-tune', 'entity': 'wtmlon', 'root_dir': '/lt/DART', 'run_id': 'vyuohhgq', 'sweep_param_path': '/lt/DART/wandb/sweep-in2rb94g/config-vyuohhgq.yaml', 'sweep_id': 'in2rb94g'}
2022-03-11 05:06:23,433 INFO    Thread-7  :47816 [wandb_init.py:_log_setup():336] Logging user logs to /lt/DART/wandb/run-20220311_050623-vyuohhgq/logs/debug.log
2022-03-11 05:06:23,434 INFO    Thread-7  :47816 [wandb_init.py:_log_setup():337] Logging internal logs to /lt/DART/wandb/run-20220311_050623-vyuohhgq/logs/debug-internal.log
2022-03-11 05:06:23,434 INFO    Thread-7  :47816 [wandb_init.py:init():369] calling init triggers
2022-03-11 05:06:23,434 INFO    Thread-7  :47816 [wandb_init.py:init():374] wandb.init called with sweep_config: {'batch_size': 4, 'encoder_type': 'mlp', 'learning_rate': 1e-06, 'seed_split': 13, 'task': 'SST-2', 'weight_decay': 0.01, 'x_input': 'mix'}
config: {}
2022-03-11 05:06:23,434 INFO    Thread-7  :47816 [wandb_init.py:init():418] starting backend
2022-03-11 05:06:23,434 INFO    Thread-7  :47816 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-11 05:06:23,440 INFO    Thread-7  :47816 [backend.py:ensure_launched():132] starting backend process...
2022-03-11 05:06:23,452 INFO    Thread-7  :47816 [backend.py:ensure_launched():136] started backend process with pid: 48042
2022-03-11 05:06:23,454 INFO    Thread-7  :47816 [wandb_init.py:init():423] backend started and connected
2022-03-11 05:06:23,455 INFO    Thread-7  :47816 [wandb_run.py:_config_callback():787] config_cb None None {'batch_size': 4, 'encoder_type': 'mlp', 'learning_rate': 1e-06, 'seed_split': 13, 'task': 'SST-2', 'weight_decay': 0.01, 'x_input': 'mix'}
2022-03-11 05:06:23,456 INFO    Thread-7  :47816 [wandb_init.py:init():465] updated telemetry
2022-03-11 05:06:23,456 INFO    Thread-7  :47816 [wandb_init.py:init():484] communicating current version
2022-03-11 05:06:28,457 INFO    Thread-7  :47816 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2022-03-11 05:06:29,723 INFO    Thread-7  :47816 [wandb_init.py:init():522] starting run threads in backend
2022-03-11 05:06:34,732 INFO    Thread-7  :47816 [wandb_run.py:_console_start():1565] atexit reg
2022-03-11 05:06:34,733 INFO    Thread-7  :47816 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2022-03-11 05:06:34,733 INFO    Thread-7  :47816 [wandb_run.py:_redirect():1417] Redirecting console.
2022-03-11 05:06:34,733 ERROR   Thread-7  :47816 [wandb_run.py:_redirect():1482] Failed to redirect.
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1475, in _redirect
    out_redir.install()
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 605, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 555, in add_fd
    self._register()
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 540, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/root/anaconda3/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2022-03-11 05:06:34,737 INFO    Thread-7  :47816 [wandb_init.py:init():546] run started, returning control to user process
2022-03-11 05:06:36,057 INFO    Thread-12 :47816 [wandb_setup.py:_flush():69] setting env: {'project': 'L-tune', 'entity': 'wtmlon', 'root_dir': '/lt/DART', 'run_id': 'oafyz093', 'sweep_param_path': '/lt/DART/wandb/sweep-in2rb94g/config-oafyz093.yaml', 'sweep_id': 'in2rb94g'}
2022-03-11 05:06:36,057 INFO    Thread-12 :47816 [wandb_init.py:_log_setup():336] Logging user logs to /lt/DART/wandb/run-20220311_050636-oafyz093/logs/debug.log
2022-03-11 05:06:36,058 INFO    Thread-12 :47816 [wandb_init.py:_log_setup():337] Logging internal logs to /lt/DART/wandb/run-20220311_050636-oafyz093/logs/debug-internal.log
2022-03-11 05:06:36,058 INFO    Thread-12 :47816 [wandb_init.py:init():369] calling init triggers
2022-03-11 05:06:36,058 INFO    Thread-12 :47816 [wandb_init.py:init():374] wandb.init called with sweep_config: {'batch_size': 4, 'encoder_type': 'mlp', 'learning_rate': 1e-06, 'seed_split': 13, 'task': 'SST-2', 'weight_decay': 0.05, 'x_input': 'mix'}
config: {}
2022-03-11 05:06:36,058 INFO    Thread-12 :47816 [wandb_init.py:init():418] starting backend
2022-03-11 05:06:36,058 INFO    Thread-12 :47816 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-11 05:06:36,064 INFO    Thread-12 :47816 [backend.py:ensure_launched():132] starting backend process...
2022-03-11 05:06:36,075 INFO    Thread-12 :47816 [backend.py:ensure_launched():136] started backend process with pid: 48131
2022-03-11 05:06:36,077 INFO    Thread-12 :47816 [wandb_init.py:init():423] backend started and connected
2022-03-11 05:06:36,078 INFO    Thread-12 :47816 [wandb_run.py:_config_callback():787] config_cb None None {'batch_size': 4, 'encoder_type': 'mlp', 'learning_rate': 1e-06, 'seed_split': 13, 'task': 'SST-2', 'weight_decay': 0.05, 'x_input': 'mix'}
2022-03-11 05:06:36,079 INFO    Thread-12 :47816 [wandb_init.py:init():465] updated telemetry
2022-03-11 05:06:36,080 INFO    Thread-12 :47816 [wandb_init.py:init():484] communicating current version
2022-03-11 05:06:41,080 INFO    Thread-12 :47816 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2022-03-11 05:06:42,298 INFO    Thread-12 :47816 [wandb_init.py:init():522] starting run threads in backend
2022-03-11 05:06:47,313 ERROR   Thread-12 :47816 [wandb_init.py:init():770] error
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 744, in init
    run = wi.init()
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 525, in init
    _ = backend.interface.communicate_run_start(run_obj)
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 799, in communicate_run_start
    result = self._communicate(rec)
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 537, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/root/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 82, in get
    is_set = self._object_ready.wait(timeout)
  File "/root/anaconda3/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/root/anaconda3/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
Exception
2022-03-11 05:06:48,808 INFO    MainThread:47816 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 2
2022-03-11 05:06:48,809 INFO    MainThread:47816 [wandb_run.py:_restore():1507] restore
2022-03-11 05:06:48,809 INFO    MainThread:47816 [wandb_run.py:_restore():1507] restore
2022-03-11 05:06:48,814 INFO    MainThread:47816 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 2
2022-03-11 05:06:48,814 INFO    MainThread:47816 [wandb_run.py:_restore():1507] restore
2022-03-11 05:06:48,815 INFO    MainThread:47816 [wandb_run.py:_restore():1507] restore
